"""Deterministic sample profiles used by demo mode.

No real people, no scraped PII. One profile deliberately uses
``candidate@doodle.com`` so the candidate portal has something to show when you
log in with that demo account.
"""
from __future__ import annotations

SAMPLE_PROFILES: list[dict] = [
    {"username": "ada-codes", "name": "Ada Lin", "email": "candidate@doodle.com",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=ada",
     "followers": 1820, "public_repos": 74, "public_gists": 31,
     "languages": "Python, TypeScript, Rust, Go"},
    {"username": "grace-hops", "name": "Grace Ophelia", "email": None,
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=grace",
     "followers": 940, "public_repos": 51, "public_gists": 12,
     "languages": "Python, C++, Julia"},
    {"username": "linus-t", "name": "Linus T.", "email": "linus@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=linus",
     "followers": 5400, "public_repos": 22, "public_gists": 3,
     "languages": "C, Shell"},
    {"username": "margaret-h", "name": "Margaret H.", "email": "margaret@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=margaret",
     "followers": 320, "public_repos": 38, "public_gists": 22,
     "languages": "Python, JavaScript, HTML, CSS"},
    {"username": "dennis-r", "name": "Dennis R.", "email": None,
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=dennis",
     "followers": 2100, "public_repos": 15, "public_gists": 1,
     "languages": "C, Assembly"},
    {"username": "barbara-l", "name": "Barbara L.", "email": "barbara@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=barbara",
     "followers": 610, "public_repos": 63, "public_gists": 40,
     "languages": "Python, TypeScript, Java, Kotlin, Swift"},
    {"username": "guido-py", "name": "Guido V.", "email": "guido@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=guido",
     "followers": 3300, "public_repos": 29, "public_gists": 9,
     "languages": "Python, C"},
    {"username": "katherine-j", "name": "Katherine J.", "email": None,
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=katherine",
     "followers": 145, "public_repos": 12, "public_gists": 2,
     "languages": "MATLAB, Python"},
    {"username": "james-g", "name": "James G.", "email": "james@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=james",
     "followers": 780, "public_repos": 44, "public_gists": 18,
     "languages": "Go, TypeScript, Python"},
    {"username": "radia-p", "name": "Radia P.", "email": "radia@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=radia",
     "followers": 260, "public_repos": 33, "public_gists": 7,
     "languages": "C++, Rust"},
    {"username": "tim-bl", "name": "Tim B-L.", "email": None,
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=tim",
     "followers": 4100, "public_repos": 19, "public_gists": 5,
     "languages": "JavaScript, HTML, CSS, TypeScript"},
    {"username": "sophie-w", "name": "Sophie W.", "email": "sophie@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=sophie",
     "followers": 55, "public_repos": 8, "public_gists": 0,
     "languages": "Python"},
    {"username": "raj-n", "name": "Raj N.", "email": "raj@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=raj",
     "followers": 990, "public_repos": 58, "public_gists": 25,
     "languages": "Java, Kotlin, Go, TypeScript"},
    {"username": "elena-v", "name": "Elena V.", "email": None,
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=elena",
     "followers": 430, "public_repos": 27, "public_gists": 11,
     "languages": "Ruby, JavaScript, Python"},
    {"username": "mateo-s", "name": "Mateo S.", "email": "mateo@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=mateo",
     "followers": 1250, "public_repos": 41, "public_gists": 14,
     "languages": "Rust, Go, C++, Python"},
    {"username": "yuki-t", "name": "Yuki T.", "email": "yuki@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=yuki",
     "followers": 88, "public_repos": 19, "public_gists": 4,
     "languages": "TypeScript, JavaScript"},
    {"username": "amir-k", "name": "Amir K.", "email": None,
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=amir",
     "followers": 2750, "public_repos": 67, "public_gists": 29,
     "languages": "Python, TypeScript, Go, Rust, C++"},
    {"username": "nina-b", "name": "Nina B.", "email": "nina@example.dev",
     "avatar_url": "https://api.dicebear.com/9.x/thumbs/svg?seed=nina",
     "followers": 175, "public_repos": 22, "public_gists": 6,
     "languages": "C#, TypeScript, F#"},
]
